---
- name: Check OS version
  hosts: routeros
  gather_facts: no

  connection: network_cli
  tasks:
  - name: check OS version on device routeros
    routeros_command:
      commands: /system package print
    register: version_output

  - debug:
      var: version_output

  - name: Set timezone to Auckland
    routeros_command:
      commands: /system clock set time-zone-name=Pacific/Auckland

  - name: Set allow remote DNS to false
    routeros_command:
      commands: /ip dns set allow-remote-requests=no

  - name: Set ip socks to disable
    routeros_command:
      commands: /ip socks set enabled=no

  