---
- name: "Check OS version"
  hosts: routeros
  gather_facts: no

  tasks:
    - name: check OS version on device routeros
     routeros_command:
      commands: /system package print
    register: version_output
    - name: Display facts variables
     debug:
      var: version_output
