---
- name: Check OS version
  hosts: routeros
  gather_facts: no

  connection: network_cli
  tasks:
  - name: check OS version on device routeros
    routeros_command:
      commands: /system package print
    register: version_output

  - debug:
      var: version_output

  - name: Set timezone to Auckland
    routeros_command:
      commands: /system clock set time-zone-name=Pacific/Auckland

  - name: Set allow remote DNS to false
    routeros_command:
      commands: /ip dns set allow-remote-requests=no

  - name: Set ip socks to disable
    routeros_command:
      commands: /ip socks set enabled=no

  - name: Set RFC6890 address list
    routeros_command:
      command: /ip firewall address-list 
                  add address=0.0.0.0/8 comment=RFC6890 list=not_in_internet 
                  add address=10.0.0.0/8 comment=RFC6890 list=not_in_internet
                  add address=100.64.0.0/10 comment=RFC6890 list=not_in_internet
                  add address=127.0.0.0/8 comment=RFC6890 list=not_in_internet
                  add address=169.254.0.0/16 comment=RFC6890 list=not_in_internet
                  add address=172.16.0.0/12 comment=RFC6890 list=not_in_internet
                  add address=192.0.0.0/24 comment=RFC6890 list=not_in_internet
                  add address=192.0.2.0/24 comment=RFC6890 list=not_in_internet
                  add address=192.88.99.0/24 comment="6to4 relay Anycast [RFC 3068]" list=not_in_internet
                  add address=192.168.0.0/16 comment=RFC6890 list=not_in_internet
                  add address=198.18.0.0/15 comment=RFC6890 list=not_in_internet
                  add address=198.51.100.0/24 comment=RFC6890 list=not_in_internet
                  add address=203.0.113.0/24 comment=RFC6890 list=not_in_internet
                  add address=224.0.0.0/4 comment=Multicast list=not_in_internet
                  add address=240.0.0.0/4 comment=RFC6890 list=not_in_internet


  