---
- name: Check OS version
  hosts: routeros
  gather_facts: no

  connection: network_cli
  tasks:
  - name: check OS version on device routeros
    routeros_command:
      commands: /system package print
    register: version_output

  - debug:
      var: version_output

  - name: Set timezone to Auckland
    routeros_command:
      commands: /system clock set time-zone-name=Pacific/Auckland

  - name: Set allow remote DNS to false
    routeros_command:
      commands: /ip dns set allow-remote-requests=no

  - name: Set ip socks to disable
    routeros_command:
      commands: /ip socks set enabled=no

  - name: run command on remote devices
    routeros_command:
      commands: /system routerboard print

  - name: run command and check to see if output contains routeros
    routeros_command:
      commands: /system resource print
      wait_for: result[0] contains MikroTik

  - name: run multiple commands on remote nodes
    routeros_command:
      commands:
        - /system routerboard print
        - /system identity print

  - name: run multiple commands and evaluate the output
    routeros_command:
      commands:
        - /system routerboard print
        - /interface ethernet print
      wait_for:
        - result[0] contains x86
        - result[1] contains ether1