---
- hosts: 192.168.1.198
  connection: network_cli
  gather_facts: False
  tasks:
    - name: run show version
      ios_facts:
      lines: hostname {{ inventory_hostname }}
    - debug:
        var: ansible_net_version